### ISSUE TITLE
Installation problems on 3.1.9

### ISSUE THREAD

**Issue by ellisonbg** [jupytercalpoly/jupyterlab-comments#140]
I created a clean conda env with JupyterLab 3.1.9 and installed jupyterlab-comments, but I don't see any of the UI elements for the extension. No messages in the browser console. Has anyone tried this combination?

**Comment by cameron-toy** [comment]
I built the package wrong for 0.1.1. 0.1.2 should install correctly--please let me know if the issue persists.

**Comment by srirag-vuppala** [comment]
Just tried this combination; it seems like 0.1.2 fixed the issue in regards to our extension. 

To actually get things started with JupyterLab=3.1.9 I had to downgrade the jupyter-server due to a conflict with nbclassic (documented [here](https://github.com/jupyterlab/jupyterlab/issues/10228)).

A tangential issue I've noticed is that extensions do not appear in the extensions tab of the UI.
