### ISSUE TITLE
shift+enter or alt+enter for newline submits comment

### ISSUE THREAD

**Issue by aiqc** [jupytercalpoly/jupyterlab-comments#92]
![image](https://user-images.githubusercontent.com/74990642/127367153-c64164a5-f99f-42b3-aa21-c9ac1f8e553b.png)

<kbd>Shift</kbd> + <kbd>Return</kbd>

and 

<kbd>Alt</kbd> + <kbd>Return</kbd>

are commonly used conventions to enter a new line without submitting state. but both submit state in a comment

**Comment by srirag-vuppala** [comment]
Hello @aiqc , Thanks for the issue!

The present implementation allows for <kbd>Shift</kbd> + <kbd>Return</kbd> for the addition of replies and editing of comments. I see how the dialog box that pops up in the add comment doesn't seem to have that functionality. We'll try and address this by moving away from the `InputDialog` to a more custom input textbox.

In regards to the <kbd>Alt</kbd> + <kbd>Return</kbd> we'll be giving it more thought since we might have conflicts with users on other OS's like windows.
